name: Storybook Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/shared-deploy.yml
    secrets: inherit
    with:
      domain: "uikit.aragon.org"
