name: Storybook Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: aragon/gov-ui-kit/.github/actions/setup@main
      - name: Deploy Storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn install --immutable
          build_command: yarn build:storybook
          path: storybook-static
          checkout: false
