name: Storybook Preview Deploy

on:
  pull_request:
    types:
      - labeled
      - synchronize

env:
  NODE_VERSION: 16
  NODE_CACHE: "yarn"

jobs:
  deploy-preview:
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build storybook
        run: yarn build:storybook
      - name: Get previous deployment
        uses: peter-evans/find-comment@v2.4.0
        id: get-deployment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "Storybook IPFS Hash: "
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install pyyaml
        run: pip install --user pyyaml packaging
      - name: Install ipfs-cluster-ctl
        run: |
          wget https://dist.ipfs.io/ipfs-cluster-ctl/v1.0.0/ipfs-cluster-ctl_v1.0.0_linux-amd64.tar.gz
          tar xvfz ipfs-cluster-ctl_v1.0.0_linux-amd64.tar.gz
      - name: Unpin from IPFS
        continue-on-error: true
        if: steps.get-deployment.outputs.comment-id != 0
        run: |
          COMMENT='${{ steps.get-deployment.outputs.comment-body }}'
          IFS=" " read -ra array <<< "$COMMENT"
          hash=${array[3]}
          ./ipfs-cluster-ctl/ipfs-cluster-ctl --basic-auth '${{ secrets.IPFS_BASIC_AUTH }}' --host '${{ secrets.IPFS_HOST }}' pin rm $hash
      - name: Pin on IPFS
        id: ipfs-pin
        run: |
          ipfsResult="$(./ipfs-cluster-ctl/ipfs-cluster-ctl --basic-auth '${{ secrets.IPFS_BASIC_AUTH }}' --host '${{ secrets.IPFS_HOST }}' add -r './storybook-static' | tail -1)"
          IFS=" " read -ra array <<< "$ipfsResult"
          echo "hash=${array[1]}" >> $GITHUB_OUTPUT
      - name: Echo url
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Storybook IPFS Hash: ${{ steps.ipfs-pin.outputs.hash }}
            ODS deployed to https://ipfs.eth.aragon.network/ipfs/${{ steps.ipfs-pin.outputs.hash }}/
